// Inventario inicial generado desde la pestaña ESPEJOS.
window.mirrorInitialProducts = [
  {
    "code": "388-CVD131C",
    "name": "AVEO SEDAN MANUAL (05-14)",
    "provider": "TYC OKLA",
    "mirrorLeft": 0,
    "mirrorRight": 0,
    "coverLeft": 0,
    "coverRight": 0,
    "glassLeft": 0,
    "glassRight": 0,
    "total": 0,
    "unitCost": 78000,
    "unitPrice": 110000,
    "source": "INVENTARIO CITY STOP.xlsx / ESPEJOS",
    "active": true,
    "id": "388-CVD131C",
    "sideTotal": 0
  },
  {
    "code": "388-CVD145C",
    "name": "AVEO EMOTION MANUAL (06-14)",
    "provider": "TYC OKLA",
    "mirrorLeft": 1,
    "mirrorRight": 1,
    "coverLeft": 0,
    "coverRight": 0,
    "glassLeft": 0,
    "glassRight": 0,
    "total": 2,
    "unitCost": 96000,
    "unitPrice": 135000,
    "source": "INVENTARIO CITY STOP.xlsx / ESPEJOS",
    "active": true,
    "id": "388-CVD145C",
    "sideTotal": 2
  },
  {
    "code": "388-CVD173C",
    "name": "SPARK GT MANUAL (10-14)",
    "provider": "TYC OKLA",
    "mirrorLeft": 0,
    "mirrorRight": 1,
    "coverLeft": 0,
    "coverRight": 0,
    "glassLeft": 0,
    "glassRight": 0,
    "total": 1,
    "unitCost": 118000,
    "unitPrice": 170000,
    "source": "INVENTARIO CITY STOP.xlsx / ESPEJOS",
    "active": true,
    "id": "388-CVD173C",
    "sideTotal": 1
  },
  {
    "code": "388-CVD173E",
    "name": "SPARK GT ELECTRICO (10-14)",
    "provider": "TYC OKLA",
    "mirrorLeft": 1,
    "mirrorRight": 0,
    "coverLeft": 0,
    "coverRight": 0,
    "glassLeft": 0,
    "glassRight": 0,
    "total": 1,
    "unitCost": 143000,
    "unitPrice": 200000,
    "source": "INVENTARIO CITY STOP.xlsx / ESPEJOS",
    "active": true,
    "id": "388-CVD173E",
    "sideTotal": 1
  },
  {
    "code": "388-DAC003P",
    "name": "LOGAN - SANDERO (11-15) DUSTER (10-14) GRIS",
    "provider": "TYC OKLA",
    "mirrorLeft": 0,
    "mirrorRight": 0,
    "coverLeft": 1,
    "coverRight": 1,
    "glassLeft": 0,
    "glassRight": 0,
    "total": 2,
    "unitCost": 25000,
    "unitPrice": 50000,
    "source": "INVENTARIO CITY STOP.xlsx / ESPEJOS",
    "active": true,
    "id": "388-DAC003P",
    "sideTotal": 2
  },
  {
    "code": "388-DAD003C",
    "name": "LOGAN-SANDERO (11-15) DUSTER (10-14) MANUAL",
    "provider": "TYC OKLA",
    "mirrorLeft": 1,
    "mirrorRight": 1,
    "coverLeft": 0,
    "coverRight": 0,
    "glassLeft": 0,
    "glassRight": 0,
    "total": 2,
    "unitCost": 65000,
    "unitPrice": 100000,
    "source": "INVENTARIO CITY STOP.xlsx / ESPEJOS",
    "active": true,
    "id": "388-DAD003C",
    "sideTotal": 2
  },
  {
    "code": "388-DAD003T",
    "name": "LOGAN (11-15)  SANDERO (09---) ELECTRICO",
    "provider": "TYC OKLA",
    "mirrorLeft": 1,
    "mirrorRight": 1,
    "coverLeft": 0,
    "coverRight": 0,
    "glassLeft": 0,
    "glassRight": 0,
    "total": 2,
    "unitCost": 95000,
    "unitPrice": 140000,
    "source": "INVENTARIO CITY STOP.xlsx / ESPEJOS",
    "active": true,
    "id": "388-DAD003T",
    "sideTotal": 2
  },
  {
    "code": "388-DAD007C",
    "name": "DUSTER MANUAL (16-21)",
    "provider": "TYC OKLA",
    "mirrorLeft": 1,
    "mirrorRight": 1,
    "coverLeft": 0,
    "coverRight": 0,
    "glassLeft": 0,
    "glassRight": 0,
    "total": 2,
    "unitCost": 86000,
    "unitPrice": 150000,
    "source": "INVENTARIO CITY STOP.xlsx / ESPEJOS",
    "active": true,
    "id": "388-DAD007C",
    "sideTotal": 2
  },
  {
    "code": "388-DAD007T",
    "name": "DUSTER ELECTRICO - DESEMPAÑANTE (16-21)",
    "provider": "TYC OKLA",
    "mirrorLeft": 1,
    "mirrorRight": 1,
    "coverLeft": 0,
    "coverRight": 0,
    "glassLeft": 0,
    "glassRight": 0,
    "total": 2,
    "unitCost": 108000,
    "unitPrice": 180000,
    "source": "INVENTARIO CITY STOP.xlsx / ESPEJOS",
    "active": true,
    "id": "388-DAD007T",
    "sideTotal": 2
  },
  {
    "code": "388-DAD009C",
    "name": "KANGO (2020)",
    "provider": "TYC OKLA",
    "mirrorLeft": 1,
    "mirrorRight": 1,
    "coverLeft": 0,
    "coverRight": 0,
    "glassLeft": 0,
    "glassRight": 0,
    "total": 2,
    "unitCost": 90000,
    "unitPrice": 180000,
    "source": "INVENTARIO CITY STOP.xlsx / ESPEJOS",
    "active": true,
    "id": "388-DAD009C",
    "sideTotal": 2
  },
  {
    "code": "388-DWD039C",
    "name": "SPARK CRONOS MANUAL (05 - 14)",
    "provider": "TYC OKLA",
    "mirrorLeft": 1,
    "mirrorRight": 1,
    "coverLeft": 0,
    "coverRight": 0,
    "glassLeft": 0,
    "glassRight": 0,
    "total": 2,
    "unitCost": 85000,
    "unitPrice": 130000,
    "source": "INVENTARIO CITY STOP.xlsx / ESPEJOS",
    "active": true,
    "id": "388-DWD039C",
    "sideTotal": 2
  },
  {
    "code": "388-FDD502TPL1",
    "name": "FIESTA ELECTRICO - DESEMPAÑANTE GRIS CON LUZ (14-16)",
    "provider": "TYC OKLA",
    "mirrorLeft": 0,
    "mirrorRight": 0,
    "coverLeft": 0,
    "coverRight": 0,
    "glassLeft": 0,
    "glassRight": 0,
    "total": 0,
    "unitCost": 156000,
    "unitPrice": 230000,
    "source": "INVENTARIO CITY STOP.xlsx / ESPEJOS",
    "active": true,
    "id": "388-FDD502TPL1",
    "sideTotal": 0
  },
  {
    "code": "388-FDD521EPL",
    "name": "ECOSPORT ELECTRICO - DIRECCIONAL GRIS (15-18)",
    "provider": "TYC OKLA",
    "mirrorLeft": 1,
    "mirrorRight": 1,
    "coverLeft": 0,
    "coverRight": 0,
    "glassLeft": 0,
    "glassRight": 0,
    "total": 2,
    "unitCost": 165000,
    "unitPrice": 250000,
    "source": "INVENTARIO CITY STOP.xlsx / ESPEJOS",
    "active": true,
    "id": "388-FDD521EPL",
    "sideTotal": 2
  },
  {
    "code": "388-HND091C",
    "name": "VISION LARGO MANUAL (06-09)",
    "provider": "TYC OKLA",
    "mirrorLeft": 0,
    "mirrorRight": 0,
    "coverLeft": 0,
    "coverRight": 0,
    "glassLeft": 0,
    "glassRight": 0,
    "total": 0,
    "unitCost": 88000,
    "unitPrice": 130000,
    "source": "INVENTARIO CITY STOP.xlsx / ESPEJOS",
    "active": true,
    "id": "388-HND091C",
    "sideTotal": 0
  },
  {
    "code": "388-IZD039",
    "name": "NPR GRANDE (98-12)",
    "provider": "TYC OKLA",
    "mirrorLeft": 1,
    "mirrorRight": 1,
    "coverLeft": 0,
    "coverRight": 0,
    "glassLeft": 0,
    "glassRight": 0,
    "total": 2,
    "unitCost": 20000,
    "unitPrice": 50000,
    "source": "INVENTARIO CITY STOP.xlsx / ESPEJOS",
    "active": true,
    "id": "388-IZD039",
    "sideTotal": 2
  },
  {
    "code": "388-IZD040",
    "name": "NKR PEQUEÑO (98-12)",
    "provider": "TYC OKLA",
    "mirrorLeft": 2,
    "mirrorRight": 2,
    "coverLeft": 0,
    "coverRight": 0,
    "glassLeft": 0,
    "glassRight": 0,
    "total": 4,
    "unitCost": 16000,
    "unitPrice": 40000,
    "source": "INVENTARIO CITY STOP.xlsx / ESPEJOS",
    "active": true,
    "id": "388-IZD040",
    "sideTotal": 4
  },
  {
    "code": "388-IZD063EB",
    "name": "DIMAX ELECTRICO (05-12)",
    "provider": "TYC OKLA",
    "mirrorLeft": 1,
    "mirrorRight": 1,
    "coverLeft": 0,
    "coverRight": 0,
    "glassLeft": 0,
    "glassRight": 0,
    "total": 2,
    "unitCost": 115000,
    "unitPrice": 170000,
    "source": "INVENTARIO CITY STOP.xlsx / ESPEJOS",
    "active": true,
    "id": "388-IZD063EB",
    "sideTotal": 2
  },
  {
    "code": "388-IZD063MB",
    "name": "DIMAX MANUAL (05-12)",
    "provider": "TYC OKLA",
    "mirrorLeft": 1,
    "mirrorRight": 1,
    "coverLeft": 0,
    "coverRight": 0,
    "glassLeft": 0,
    "glassRight": 0,
    "total": 2,
    "unitCost": 65000,
    "unitPrice": 100000,
    "source": "INVENTARIO CITY STOP.xlsx / ESPEJOS",
    "active": true,
    "id": "388-IZD063MB",
    "sideTotal": 2
  },
  {
    "code": "388-KAD091",
    "name": "PICANTO MORNING MANUAL (08-10)",
    "provider": "TYC OKLA",
    "mirrorLeft": 1,
    "mirrorRight": 1,
    "coverLeft": 0,
    "coverRight": 0,
    "glassLeft": 0,
    "glassRight": 0,
    "total": 2,
    "unitCost": 94000,
    "unitPrice": 130000,
    "source": "INVENTARIO CITY STOP.xlsx / ESPEJOS",
    "active": true,
    "id": "388-KAD091",
    "sideTotal": 2
  },
  {
    "code": "388-MZD019",
    "name": "323 MANUAL (83-04)",
    "provider": "TYC OKLA",
    "mirrorLeft": 2,
    "mirrorRight": 2,
    "coverLeft": 0,
    "coverRight": 0,
    "glassLeft": 0,
    "glassRight": 0,
    "total": 4,
    "unitCost": 30000,
    "unitPrice": 60000,
    "source": "INVENTARIO CITY STOP.xlsx / ESPEJOS",
    "active": true,
    "id": "388-MZD019",
    "sideTotal": 4
  },
  {
    "code": "388-MZD169EC",
    "name": "BT50 CROMADO ELECTRICO (07-15)",
    "provider": "TYC OKLA",
    "mirrorLeft": 1,
    "mirrorRight": 0,
    "coverLeft": 0,
    "coverRight": 0,
    "glassLeft": 0,
    "glassRight": 0,
    "total": 1,
    "unitCost": 140000,
    "unitPrice": 200000,
    "source": "INVENTARIO CITY STOP.xlsx / ESPEJOS",
    "active": true,
    "id": "388-MZD169EC",
    "sideTotal": 1
  },
  {
    "code": "388-MZD169MC",
    "name": "BT50 CROMADO MANUAL (07-15)",
    "provider": "TYC OKLA",
    "mirrorLeft": 1,
    "mirrorRight": 1,
    "coverLeft": 0,
    "coverRight": 0,
    "glassLeft": 0,
    "glassRight": 0,
    "total": 2,
    "unitCost": 105000,
    "unitPrice": 160000,
    "source": "INVENTARIO CITY STOP.xlsx / ESPEJOS",
    "active": true,
    "id": "388-MZD169MC",
    "sideTotal": 2
  },
  {
    "code": "388-NSD247M",
    "name": "SENTRA B13 MANUAL (93-95)",
    "provider": "TYC OKLA",
    "mirrorLeft": 1,
    "mirrorRight": 1,
    "coverLeft": 0,
    "coverRight": 0,
    "glassLeft": 0,
    "glassRight": 0,
    "total": 2,
    "unitCost": 30000,
    "unitPrice": 60000,
    "source": "INVENTARIO CITY STOP.xlsx / ESPEJOS",
    "active": true,
    "id": "388-NSD247M",
    "sideTotal": 2
  },
  {
    "code": "388-NSD262N",
    "name": "URVAN MANUAL (10-14)",
    "provider": "TYC OKLA",
    "mirrorLeft": 1,
    "mirrorRight": 1,
    "coverLeft": 0,
    "coverRight": 0,
    "glassLeft": 0,
    "glassRight": 0,
    "total": 2,
    "unitCost": 35000,
    "unitPrice": 70000,
    "source": "INVENTARIO CITY STOP.xlsx / ESPEJOS",
    "active": true,
    "id": "388-NSD262N",
    "sideTotal": 2
  },
  {
    "code": "388-NSD375CP",
    "name": "MARCH MANUAL GRIS (13-20)",
    "provider": "TYC OKLA",
    "mirrorLeft": 0,
    "mirrorRight": 1,
    "coverLeft": 0,
    "coverRight": 0,
    "glassLeft": 0,
    "glassRight": 0,
    "total": 1,
    "unitCost": 95000,
    "unitPrice": 150000,
    "source": "INVENTARIO CITY STOP.xlsx / ESPEJOS",
    "active": true,
    "id": "388-NSD375CP",
    "sideTotal": 1
  },
  {
    "code": "388-NSD435MB",
    "name": "URBAN E26 MANUAL (15-18)",
    "provider": "TYC OKLA",
    "mirrorLeft": 0,
    "mirrorRight": 0,
    "coverLeft": 0,
    "coverRight": 0,
    "glassLeft": 0,
    "glassRight": 0,
    "total": 0,
    "unitCost": 75000,
    "unitPrice": 120000,
    "source": "INVENTARIO CITY STOP.xlsx / ESPEJOS",
    "active": true,
    "id": "388-NSD435MB",
    "sideTotal": 0
  },
  {
    "code": "388-OPD003H",
    "name": "CORSA WIN - ACTIVE - SEDAN (96-04)",
    "provider": "TYC OKLA",
    "mirrorLeft": 1,
    "mirrorRight": 1,
    "coverLeft": 0,
    "coverRight": 0,
    "glassLeft": 0,
    "glassRight": 0,
    "total": 2,
    "unitCost": 38000,
    "unitPrice": 80000,
    "source": "INVENTARIO CITY STOP.xlsx / ESPEJOS",
    "active": true,
    "id": "388-OPD003H",
    "sideTotal": 2
  },
  {
    "code": "388-OPD053C",
    "name": "CORSA EVOLUTION MANUAL (03-07)",
    "provider": "TYC OKLA",
    "mirrorLeft": 1,
    "mirrorRight": 1,
    "coverLeft": 0,
    "coverRight": 0,
    "glassLeft": 0,
    "glassRight": 0,
    "total": 2,
    "unitCost": 64000,
    "unitPrice": 100000,
    "source": "INVENTARIO CITY STOP.xlsx / ESPEJOS",
    "active": true,
    "id": "388-OPD053C",
    "sideTotal": 2
  },
  {
    "code": "388-RNC105P",
    "name": "TAPA CLIO - SIMBOL GRIS (03-15)",
    "provider": "TYC OKLA",
    "mirrorLeft": 0,
    "mirrorRight": 0,
    "coverLeft": 2,
    "coverRight": 2,
    "glassLeft": 0,
    "glassRight": 0,
    "total": 4,
    "unitCost": 21000,
    "unitPrice": 45000,
    "source": "INVENTARIO CITY STOP.xlsx / ESPEJOS",
    "active": true,
    "id": "388-RNC105P",
    "sideTotal": 4
  },
  {
    "code": "388-RNC193P",
    "name": "LOGAN - SANDERO (16 ----) SIN LUZ",
    "provider": "TYC OKLA",
    "mirrorLeft": 0,
    "mirrorRight": 0,
    "coverLeft": 2,
    "coverRight": 2,
    "glassLeft": 0,
    "glassRight": 0,
    "total": 4,
    "unitCost": 31000,
    "unitPrice": 50000,
    "source": "INVENTARIO CITY STOP.xlsx / ESPEJOS",
    "active": true,
    "id": "388-RNC193P",
    "sideTotal": 4
  },
  {
    "code": "388-RNC193P",
    "name": "LOGAN - SANDERO (16 ----) CON LUZ",
    "provider": "TYC OKLA",
    "mirrorLeft": 0,
    "mirrorRight": 0,
    "coverLeft": 2,
    "coverRight": 2,
    "glassLeft": 0,
    "glassRight": 0,
    "total": 2,
    "unitCost": 30000,
    "unitPrice": 50000,
    "source": "INVENTARIO CITY STOP.xlsx / ESPEJOS",
    "active": true,
    "id": "388-RNC193P",
    "sideTotal": 4
  },
  {
    "code": "388-RND017M",
    "name": "TWINGO MANUAL (96-13)",
    "provider": "TYC OKLA",
    "mirrorLeft": 0,
    "mirrorRight": 1,
    "coverLeft": 0,
    "coverRight": 0,
    "glassLeft": 0,
    "glassRight": 0,
    "total": 1,
    "unitCost": 57000,
    "unitPrice": 100000,
    "source": "INVENTARIO CITY STOP.xlsx / ESPEJOS",
    "active": true,
    "id": "388-RND017M",
    "sideTotal": 1
  },
  {
    "code": "388-RND019C",
    "name": "MEGANE 1 MANUAL (02-08)",
    "provider": "TYC OKLA",
    "mirrorLeft": 1,
    "mirrorRight": 1,
    "coverLeft": 0,
    "coverRight": 0,
    "glassLeft": 0,
    "glassRight": 0,
    "total": 2,
    "unitCost": 68000,
    "unitPrice": 130000,
    "source": "INVENTARIO CITY STOP.xlsx / ESPEJOS",
    "active": true,
    "id": "388-RND019C",
    "sideTotal": 2
  },
  {
    "code": "388-RND021C",
    "name": "CLIO MANUAL (98-02)",
    "provider": "TYC OKLA",
    "mirrorLeft": 1,
    "mirrorRight": 1,
    "coverLeft": 0,
    "coverRight": 0,
    "glassLeft": 0,
    "glassRight": 0,
    "total": 2,
    "unitCost": 60000,
    "unitPrice": 120000,
    "source": "INVENTARIO CITY STOP.xlsx / ESPEJOS",
    "active": true,
    "id": "388-RND021C",
    "sideTotal": 2
  },
  {
    "code": "388-RND105C",
    "name": "CLIO - SIMBOL MANUAL  (03-15)",
    "provider": "TYC OKLA",
    "mirrorLeft": 2,
    "mirrorRight": 2,
    "coverLeft": 0,
    "coverRight": 0,
    "glassLeft": 0,
    "glassRight": 0,
    "total": 4,
    "unitCost": 55000,
    "unitPrice": 100000,
    "source": "INVENTARIO CITY STOP.xlsx / ESPEJOS",
    "active": true,
    "id": "388-RND105C",
    "sideTotal": 4
  },
  {
    "code": "388-RND105E",
    "name": "CLIO - SIMBOL ELECTRICO (03-15)",
    "provider": "TYC OKLA",
    "mirrorLeft": 1,
    "mirrorRight": 1,
    "coverLeft": 0,
    "coverRight": 0,
    "glassLeft": 0,
    "glassRight": 0,
    "total": 2,
    "unitCost": 90000,
    "unitPrice": 140000,
    "source": "INVENTARIO CITY STOP.xlsx / ESPEJOS",
    "active": true,
    "id": "388-RND105E",
    "sideTotal": 2
  },
  {
    "code": "388-RND193EPSL",
    "name": "LOGAN - SANDERO ELECTRICO CON LUZ (16 -----)",
    "provider": "TYC OKLA",
    "mirrorLeft": 3,
    "mirrorRight": 3,
    "coverLeft": 0,
    "coverRight": 0,
    "glassLeft": 0,
    "glassRight": 0,
    "total": 6,
    "unitCost": 165000,
    "unitPrice": 250000,
    "source": "INVENTARIO CITY STOP.xlsx / ESPEJOS",
    "active": true,
    "id": "388-RND193EPSL",
    "sideTotal": 6
  },
  {
    "code": "388-SZD021",
    "name": "SPRINT (88-03)",
    "provider": "TYC OKLA",
    "mirrorLeft": 2,
    "mirrorRight": 2,
    "coverLeft": 0,
    "coverRight": 0,
    "glassLeft": 0,
    "glassRight": 0,
    "total": 4,
    "unitCost": 35000,
    "unitPrice": 60000,
    "source": "INVENTARIO CITY STOP.xlsx / ESPEJOS",
    "active": true,
    "id": "388-SZD021",
    "sideTotal": 4
  },
  {
    "code": "388-SZD033",
    "name": "SUPER CARRY",
    "provider": "TYC OKLA",
    "mirrorLeft": 2,
    "mirrorRight": 2,
    "coverLeft": 0,
    "coverRight": 0,
    "glassLeft": 0,
    "glassRight": 0,
    "total": 4,
    "unitCost": 15000,
    "unitPrice": 40000,
    "source": "INVENTARIO CITY STOP.xlsx / ESPEJOS",
    "active": true,
    "id": "388-SZD033",
    "sideTotal": 4
  },
  {
    "code": "HD01-6007-H-LH",
    "name": "ACCENT (96-98)",
    "provider": "TYC OKLA",
    "mirrorLeft": 2,
    "mirrorRight": 2,
    "coverLeft": 0,
    "coverRight": 0,
    "glassLeft": 0,
    "glassRight": 0,
    "total": 4,
    "unitCost": 50000,
    "unitPrice": 80000,
    "source": "INVENTARIO CITY STOP.xlsx / ESPEJOS",
    "active": true,
    "id": "HD01-6007-H-LH",
    "sideTotal": 4
  },
  {
    "code": "HD02-20007",
    "name": "AVEO EMOTION SEDAN",
    "provider": "TODO",
    "mirrorLeft": 1,
    "mirrorRight": 1,
    "coverLeft": 0,
    "coverRight": 0,
    "glassLeft": 0,
    "glassRight": 0,
    "total": 2,
    "unitCost": 61000,
    "unitPrice": 90000,
    "source": "INVENTARIO CITY STOP.xlsx / ESPEJOS",
    "active": true,
    "id": "HD02-20007",
    "sideTotal": 2
  },
  {
    "code": "388-BZD095TL",
    "name": "SPRINTER 515 - CRAFTER, DESEMPAÑANTE",
    "provider": "TYC OKLA",
    "mirrorLeft": 1,
    "mirrorRight": 1,
    "coverLeft": 0,
    "coverRight": 0,
    "glassLeft": 0,
    "glassRight": 0,
    "total": 2,
    "unitCost": 226000,
    "unitPrice": 320000,
    "source": "INVENTARIO CITY STOP.xlsx / ESPEJOS",
    "active": true,
    "id": "388-BZD095TL",
    "sideTotal": 2
  },
  {
    "code": "388-CVG173",
    "name": "SPARK GT - BEAT",
    "provider": "INDUFAROS",
    "mirrorLeft": 0,
    "mirrorRight": 0,
    "coverLeft": 0,
    "coverRight": 0,
    "glassLeft": 2,
    "glassRight": 2,
    "total": 4,
    "unitCost": 20000,
    "unitPrice": 40000,
    "source": "INVENTARIO CITY STOP.xlsx / ESPEJOS",
    "active": true,
    "id": "388-CVG173",
    "sideTotal": 4
  },
  {
    "code": "388-FDD501TPL1",
    "name": "FIESTA ELECTRICO - CON LUZ DESEMPAÑANTE GRIS (11)",
    "provider": "TYC INDUFAROS",
    "mirrorLeft": 1,
    "mirrorRight": 1,
    "coverLeft": 0,
    "coverRight": 0,
    "glassLeft": 0,
    "glassRight": 0,
    "total": 2,
    "unitCost": 153000,
    "unitPrice": 240000,
    "source": "INVENTARIO CITY STOP.xlsx / ESPEJOS",
    "active": true,
    "id": "388-FDD501TPL1",
    "sideTotal": 2
  },
  {
    "code": "388-FDG501H",
    "name": "FIESTA 11",
    "provider": "TYC INDUFAROS",
    "mirrorLeft": 0,
    "mirrorRight": 0,
    "coverLeft": 0,
    "coverRight": 0,
    "glassLeft": 1,
    "glassRight": 1,
    "total": 2,
    "unitCost": 36500,
    "unitPrice": 55000,
    "source": "INVENTARIO CITY STOP.xlsx / ESPEJOS",
    "active": true,
    "id": "388-FDG501H",
    "sideTotal": 2
  },
  {
    "code": "388-HND157C",
    "name": "GRAN I-10 MANUAL 14",
    "provider": "TYC INDUFAROS",
    "mirrorLeft": 1,
    "mirrorRight": 1,
    "coverLeft": 0,
    "coverRight": 0,
    "glassLeft": 0,
    "glassRight": 0,
    "total": 2,
    "unitCost": 102000,
    "unitPrice": 180000,
    "source": "INVENTARIO CITY STOP.xlsx / ESPEJOS",
    "active": true,
    "id": "388-HND157C",
    "sideTotal": 2
  },
  {
    "code": "388-IZD014-1",
    "name": "LUV 2300 NEGRO (93-97)",
    "provider": "TYC INDUFAROS",
    "mirrorLeft": 2,
    "mirrorRight": 2,
    "coverLeft": 0,
    "coverRight": 0,
    "glassLeft": 0,
    "glassRight": 0,
    "total": 4,
    "unitCost": 25000,
    "unitPrice": 60000,
    "source": "INVENTARIO CITY STOP.xlsx / ESPEJOS",
    "active": true,
    "id": "388-IZD014-1",
    "sideTotal": 4
  },
  {
    "code": "388-IZD016-1",
    "name": "LUV 2300 CROMADO (93-97)",
    "provider": "TYC INDUFAROS",
    "mirrorLeft": 2,
    "mirrorRight": 2,
    "coverLeft": 0,
    "coverRight": 0,
    "glassLeft": 0,
    "glassRight": 0,
    "total": 4,
    "unitCost": 36000,
    "unitPrice": 80000,
    "source": "INVENTARIO CITY STOP.xlsx / ESPEJOS",
    "active": true,
    "id": "388-IZD016-1",
    "sideTotal": 4
  },
  {
    "code": "9031504NG",
    "name": "SAIL ELECTRICO GRIS",
    "provider": "TYC INDUFAROS",
    "mirrorLeft": 1,
    "mirrorRight": 1,
    "coverLeft": 0,
    "coverRight": 0,
    "glassLeft": 0,
    "glassRight": 0,
    "total": 2,
    "unitCost": 75000,
    "unitPrice": 140000,
    "source": "INVENTARIO CITY STOP.xlsx / ESPEJOS",
    "active": true,
    "id": "9031504NG",
    "sideTotal": 2
  },
  {
    "code": "HD06-44007",
    "name": "N300 MANUAL (12-21)",
    "provider": "TYC INDUFAROS",
    "mirrorLeft": 2,
    "mirrorRight": 2,
    "coverLeft": 0,
    "coverRight": 0,
    "glassLeft": 0,
    "glassRight": 0,
    "total": 2,
    "unitCost": 35000,
    "unitPrice": 80000,
    "source": "INVENTARIO CITY STOP.xlsx / ESPEJOS",
    "active": true,
    "id": "HD06-44007",
    "sideTotal": 4
  },
  {
    "code": "HD06-47007",
    "name": "DFSK K07",
    "provider": "TYC INDUFAROS",
    "mirrorLeft": 2,
    "mirrorRight": 2,
    "coverLeft": 0,
    "coverRight": 0,
    "glassLeft": 0,
    "glassRight": 0,
    "total": 4,
    "unitCost": 15000,
    "unitPrice": 90000,
    "source": "INVENTARIO CITY STOP.xlsx / ESPEJOS",
    "active": true,
    "id": "HD06-47007",
    "sideTotal": 4
  },
  {
    "code": "388-CVD249EP",
    "name": "ONIX ELECTRICO GRIS (17-20)",
    "provider": "TYC OKLA",
    "mirrorLeft": 1,
    "mirrorRight": 1,
    "coverLeft": 0,
    "coverRight": 0,
    "glassLeft": 0,
    "glassRight": 0,
    "total": 2,
    "unitCost": 135000,
    "unitPrice": 220000,
    "source": "INVENTARIO CITY STOP.xlsx / ESPEJOS",
    "active": true,
    "id": "388-CVD249EP",
    "sideTotal": 2
  },
  {
    "code": "388-DAD013TS",
    "name": "DUSTER ELECTRICO - DESEMPAÑANTE (22-----)",
    "provider": "TYC OKLA",
    "mirrorLeft": 1,
    "mirrorRight": 1,
    "coverLeft": 0,
    "coverRight": 0,
    "glassLeft": 0,
    "glassRight": 0,
    "total": 2,
    "unitCost": 240000,
    "unitPrice": 360000,
    "source": "INVENTARIO CITY STOP.xlsx / ESPEJOS",
    "active": true,
    "id": "388-DAD013TS",
    "sideTotal": 2
  },
  {
    "code": "388-FDD501TP1",
    "name": "FIESTA ELECTRICO DESEMPAÑANTE GRIS (11-19)",
    "provider": "TYC OKLA",
    "mirrorLeft": 1,
    "mirrorRight": 1,
    "coverLeft": 0,
    "coverRight": 0,
    "glassLeft": 0,
    "glassRight": 0,
    "total": 2,
    "unitCost": 136000,
    "unitPrice": 205000,
    "source": "INVENTARIO CITY STOP.xlsx / ESPEJOS",
    "active": true,
    "id": "388-FDD501TP1",
    "sideTotal": 2
  },
  {
    "code": "388-HND154C",
    "name": "I-25 MANUAL (12-19)",
    "provider": "TYC OKLA",
    "mirrorLeft": 1,
    "mirrorRight": 1,
    "coverLeft": 0,
    "coverRight": 0,
    "glassLeft": 0,
    "glassRight": 0,
    "total": 2,
    "unitCost": 125000,
    "unitPrice": 190000,
    "source": "INVENTARIO CITY STOP.xlsx / ESPEJOS",
    "active": true,
    "id": "388-HND154C",
    "sideTotal": 2
  },
  {
    "code": "388-RND193CP",
    "name": "LOGAN SANDERO MANUAL GRIS (16 ----)",
    "provider": "TYC OKLA",
    "mirrorLeft": 1,
    "mirrorRight": 1,
    "coverLeft": 0,
    "coverRight": 0,
    "glassLeft": 0,
    "glassRight": 0,
    "total": 2,
    "unitCost": 123000,
    "unitPrice": 185000,
    "source": "INVENTARIO CITY STOP.xlsx / ESPEJOS",
    "active": true,
    "id": "388-RND193CP",
    "sideTotal": 2
  },
  {
    "code": "388-SZD070EP",
    "name": "GRAN VITARA ELECTRICO GRIS (08-19)",
    "provider": "TYC OKLA",
    "mirrorLeft": 0,
    "mirrorRight": 0,
    "coverLeft": 0,
    "coverRight": 0,
    "glassLeft": 0,
    "glassRight": 0,
    "total": 0,
    "unitCost": 175000,
    "unitPrice": 260000,
    "source": "INVENTARIO CITY STOP.xlsx / ESPEJOS",
    "active": true,
    "id": "388-SZD070EP",
    "sideTotal": 0
  },
  {
    "code": "388-SZD113EBL",
    "name": "SWIFT HIBRIDO ELECTRICO CON LUZ (19---)",
    "provider": "TYC OKLA",
    "mirrorLeft": 1,
    "mirrorRight": 1,
    "coverLeft": 0,
    "coverRight": 0,
    "glassLeft": 0,
    "glassRight": 0,
    "total": 2,
    "unitCost": 165000,
    "unitPrice": 300000,
    "source": "INVENTARIO CITY STOP.xlsx / ESPEJOS",
    "active": true,
    "id": "388-SZD113EBL",
    "sideTotal": 2
  },
  {
    "code": "HD05-46007",
    "name": "ONIX SEDAN ELECTRICO (21----)",
    "provider": "TODO",
    "mirrorLeft": 1,
    "mirrorRight": 1,
    "coverLeft": 0,
    "coverRight": 0,
    "glassLeft": 0,
    "glassRight": 0,
    "total": 2,
    "unitCost": 112000,
    "unitPrice": 180000,
    "source": "INVENTARIO CITY STOP.xlsx / ESPEJOS",
    "active": true,
    "id": "HD05-46007",
    "sideTotal": 2
  }
];
